package com.garijotatiana.atomacademy.gui.principal;

import javax.swing.ImageIcon;



/**
 *
 * @author Tatiana
 */
//Frame auxiliar para mostrar los diferentes paneles que componene las tareas CRUD
public class frameAuxiliar extends javax.swing.JFrame {

    /**
     * Creates new form frameAuxiliar
     */
    public frameAuxiliar() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/atom.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
