package com.garijotatiana.atomacademy.gui.notas;

import com.garijotatiana.atomacademy.Auxiliar;
import com.garijotatiana.atomacademy.DAO.CursoDAO;
import com.garijotatiana.atomacademy.DAO.NotaDAO;
import com.garijotatiana.atomacademy.DAO.impl.CursoDAOImplHiber;
import com.garijotatiana.atomacademy.DAO.impl.NotaDAOImplHiber;
import com.garijotatiana.atomacademy.gui.principal.frameAuxiliar;
import com.garijotatiana.atomacademy.model.Curso;
import com.garijotatiana.atomacademy.model.Nota;
import com.garijotatiana.atomacademy.plantilla.AccionesPDF;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tatiana
 */
public class panelNotas extends javax.swing.JPanel {

    CursoDAO cursoDAO = new CursoDAOImplHiber(Curso.class);
    NotaDAO notaDAO = new NotaDAOImplHiber(Nota.class);
    List<Nota> listaCompleta = notaDAO.findAll();
    Auxiliar aux = new Auxiliar();

    public panelNotas() {
        initComponents();
        cargarTabla(listaCompleta);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        pnBotones = new javax.swing.JPanel();
        btAdd = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btPdf = new javax.swing.JButton();
        pnBuscar = new javax.swing.JPanel();
        btBuscar = new javax.swing.JButton();
        btLimpiar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        cmbBuscar = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btActualizar = new javax.swing.JButton();
        laTitulo = new javax.swing.JLabel();
        btSobresalientes = new javax.swing.JButton();
        btSuspensos = new javax.swing.JButton();
        btAprobados = new javax.swing.JButton();
        btNotables = new javax.swing.JButton();
        spTablaNotas = new javax.swing.JScrollPane();
        tbNotas = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(870, 620));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(870, 620));

        pnBotones.setOpaque(false);

        btAdd.setBackground(new java.awt.Color(140, 166, 219));
        btAdd.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btAdd.setForeground(new java.awt.Color(255, 255, 255));
        btAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mas.png"))); // NOI18N
        btAdd.setText(" Añadir");
        btAdd.setBorderPainted(false);
        btAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAdd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btEdit.setBackground(new java.awt.Color(140, 166, 219));
        btEdit.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btEdit.setForeground(new java.awt.Color(255, 255, 255));
        btEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lapiz.png"))); // NOI18N
        btEdit.setText(" Editar");
        btEdit.setBorderPainted(false);
        btEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btEdit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        btDelete.setBackground(new java.awt.Color(140, 166, 219));
        btDelete.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btDelete.setForeground(new java.awt.Color(255, 255, 255));
        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/papelera.png"))); // NOI18N
        btDelete.setText(" Eliminar");
        btDelete.setBorderPainted(false);
        btDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDelete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        btPdf.setBackground(new java.awt.Color(140, 166, 219));
        btPdf.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btPdf.setForeground(new java.awt.Color(255, 255, 255));
        btPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pdf.png"))); // NOI18N
        btPdf.setBorderPainted(false);
        btPdf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPdfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnBotonesLayout = new javax.swing.GroupLayout(pnBotones);
        pnBotones.setLayout(pnBotonesLayout);
        pnBotonesLayout.setHorizontalGroup(
            pnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBotonesLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(pnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btPdf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnBotonesLayout.setVerticalGroup(
            pnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pnBuscar.setOpaque(false);

        btBuscar.setBackground(new java.awt.Color(140, 166, 219));
        btBuscar.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar.png"))); // NOI18N
        btBuscar.setText(" Buscar");
        btBuscar.setBorderPainted(false);
        btBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btBuscar.setMargin(new java.awt.Insets(2, 2, 3, 14));
        btBuscar.setPreferredSize(new java.awt.Dimension(133, 39));
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btLimpiar.setBackground(new java.awt.Color(140, 166, 219));
        btLimpiar.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/borrar.png"))); // NOI18N
        btLimpiar.setText(" Limpiar");
        btLimpiar.setBorderPainted(false);
        btLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLimpiar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btLimpiar.setMargin(new java.awt.Insets(2, 4, 3, 14));
        btLimpiar.setMaximumSize(new java.awt.Dimension(113, 39));
        btLimpiar.setMinimumSize(new java.awt.Dimension(113, 39));
        btLimpiar.setPreferredSize(new java.awt.Dimension(133, 39));
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        cmbBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nota", "Evaluación", "Alumno", "Curso" }));
        cmbBuscar.setBackground(Color.WHITE);
        cmbBuscar.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);

        btActualizar.setBackground(new java.awt.Color(140, 166, 219));
        btActualizar.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/actualizar.png"))); // NOI18N
        btActualizar.setToolTipText("Actualizar");
        btActualizar.setBorderPainted(false);
        btActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btActualizar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btActualizar.setMargin(new java.awt.Insets(2, 4, 3, 14));
        btActualizar.setMaximumSize(new java.awt.Dimension(113, 39));
        btActualizar.setMinimumSize(new java.awt.Dimension(113, 39));
        btActualizar.setPreferredSize(new java.awt.Dimension(133, 39));
        btActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarActionPerformed(evt);
            }
        });

        laTitulo.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        laTitulo.setForeground(new java.awt.Color(79, 79, 255));
        laTitulo.setText("Registros de Notas");

        btSobresalientes.setBackground(new java.awt.Color(204, 204, 255));
        btSobresalientes.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        btSobresalientes.setForeground(new java.awt.Color(79, 79, 255));
        btSobresalientes.setText("Sobresalientes");
        btSobresalientes.setBorderPainted(false);
        btSobresalientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSobresalientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btSobresalientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSobresalientesActionPerformed(evt);
            }
        });

        btSuspensos.setBackground(new java.awt.Color(204, 204, 255));
        btSuspensos.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        btSuspensos.setForeground(new java.awt.Color(79, 79, 255));
        btSuspensos.setText("Suspensos");
        btSuspensos.setBorderPainted(false);
        btSuspensos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSuspensos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btSuspensos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuspensosActionPerformed(evt);
            }
        });

        btAprobados.setBackground(new java.awt.Color(204, 204, 255));
        btAprobados.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        btAprobados.setForeground(new java.awt.Color(79, 79, 255));
        btAprobados.setText("Aprobados");
        btAprobados.setBorderPainted(false);
        btAprobados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAprobados.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAprobados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAprobadosActionPerformed(evt);
            }
        });

        btNotables.setBackground(new java.awt.Color(204, 204, 255));
        btNotables.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        btNotables.setForeground(new java.awt.Color(79, 79, 255));
        btNotables.setText("Notables");
        btNotables.setBorderPainted(false);
        btNotables.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btNotables.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btNotables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNotablesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(laTitulo)
                .addGap(65, 65, 65)
                .addComponent(btSuspensos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAprobados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btNotables)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSobresalientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 5, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btActualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laTitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btSuspensos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btAprobados, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btNotables, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btSobresalientes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout pnBuscarLayout = new javax.swing.GroupLayout(pnBuscar);
        pnBuscar.setLayout(pnBuscarLayout);
        pnBuscarLayout.setHorizontalGroup(
            pnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBuscarLayout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbBuscar, 0, 185, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(pnBuscarLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pnBuscarLayout.setVerticalGroup(
            pnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbNotas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbNotas.setAutoscrolls(false);
        tbNotas.setPreferredSize(new java.awt.Dimension(700, 700));
        tbNotas.setSelectionBackground(new java.awt.Color(140, 166, 219));
        tbNotas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        spTablaNotas.setViewportView(tbNotas);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(spTablaNotas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(pnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spTablaNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(32, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
frameAuxiliar pantalla = new frameAuxiliar();
    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        //Comprobar que hay registro de cursos
        List<Curso> listaCursos = cursoDAO.findAll();
        if (!listaCursos.isEmpty()) {
            panelNuevoNotas panel = new panelNuevoNotas();
            JDialog dialogo = new JDialog(pantalla, "Nuevo Registro Nota", true);
            dialogo.setContentPane(panel);
            dialogo.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            dialogo.pack();
            dialogo.setLocationRelativeTo(null);
            dialogo.setVisible(true);

        } else {
            aux.mostrarMensaje("No hay registros de Cursos", "Info", "Info");
        }
    }//GEN-LAST:event_btAddActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        //controlar que la tabla no esté vacía
        if (tbNotas.getRowCount() > 0) {
            //controlar que haya un registro seleccionado
            if (tbNotas.getSelectedRow() != -1) {
                int id = (int) tbNotas.getValueAt(tbNotas.getSelectedRow(), 0);
                //Comprobar que hay registro de cursos
                List<Curso> listaCursos = cursoDAO.findAll();
                if (!listaCursos.isEmpty()) {
                    //llamda método buscar por ID
                    Nota nota = notaDAO.findById(id);

                    //abrir el panel para editar el registro 
                    panelEditarNotas panel = new panelEditarNotas(nota);

                    JDialog dialogo = new JDialog(pantalla, "Editar Registro Nota", true);
                    dialogo.setContentPane(panel);
                    dialogo.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                    dialogo.pack();
                    dialogo.setLocationRelativeTo(null);
                    dialogo.setVisible(true);

                } else {
                    aux.mostrarMensaje("No hay registros de Cursos", "Info", "Info");
                }
            } else {
                aux.mostrarMensaje("No hay ningún registro seleccionado", "Error", "Error al eliminar");
            }
        } else {
            aux.mostrarMensaje("No hay registros para editar", "Error", "Error al eliminar");
        }

    }//GEN-LAST:event_btEditActionPerformed
    List<Nota> listaBusqueda = new ArrayList<>();
    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        listaCompleta = notaDAO.findAll();

        String valorBusqueda = txtBuscar.getText();

        try {
            //controlar el el valor de busqueda no esté vacío
            if (!valorBusqueda.isEmpty() && !valorBusqueda.trim().isEmpty()) {
                String propiedad = (String) cmbBuscar.getSelectedItem();

                switch (propiedad) {
                    case "ID":
                        try {
                            int id = Integer.parseInt(valorBusqueda);
                            Nota nota = notaDAO.findById(id);
                            if (nota != null) {
                                listaBusqueda.add(nota);
                            } else {
                                aux.mostrarMensaje("No encontrado nota con el ID introducido", "Error", "Error al editar");
                            }

                        } catch (NumberFormatException e) {
                            aux.mostrarMensaje("Debe introducir un valor numérico para buscar por ID", "Error", "Error al editar");
                        } catch (Exception e) {
                            aux.mostrarMensaje("Error", "Error", "Error al editar");
                        }

                        break;

                    case "Evaluación":
                        listaBusqueda = notaDAO.findLike("evaluacion", valorBusqueda);
                        if (listaBusqueda == null || listaBusqueda.isEmpty()) {
                            aux.mostrarMensaje("No encontrado registro con los valores introducidos", "Error", "Error al editar");
                        }
                        break;

                    case "Nota":
                        try {
                            float valorNota = Float.parseFloat(valorBusqueda);
                            listaBusqueda = notaDAO.findByNota(valorNota);
                            if (listaBusqueda == null) {
                                aux.mostrarMensaje("No encontrado registro de nota con los datos introducidos", "Error", "Error al editar");
                            }
                        } catch (Exception ex) {
                            aux.mostrarMensaje("Debe introducir valor de nota válido", "Error", "Error");
                        }

                        break;

                    case "Alumno":
                        listaBusqueda = notaDAO.findNotasByAlumnoNombreOrApellidos(valorBusqueda);
                        if (listaBusqueda == null || listaBusqueda.isEmpty()) {
                            aux.mostrarMensaje("No encontrado registro de nota con los datos introducidos", "Error", "Error al editar");
                        }
                        break;

                    case "Curso":
                        listaBusqueda = notaDAO.findNotasByCursoNombre(valorBusqueda);
                        if (listaBusqueda == null || listaBusqueda.isEmpty()) {
                            aux.mostrarMensaje("No encontrado registro de nota con los datos introducidos", "Error", "Error al editar");
                        }
                        break;

                }
                cargarTabla(listaBusqueda);

            } else {
                aux.mostrarMensaje("Debe indicar un criterio de búsqueda", "Error", "Error al editar");
            }

        } catch (Exception e) {

        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        txtBuscar.setText("");
        cmbBuscar.setSelectedIndex(0);

        cargarTabla(notaDAO.findAll());
    }//GEN-LAST:event_btLimpiarActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        try {
            //controlar que la tabla no esté vacía
            if (tbNotas.getRowCount() > 0) {
                //controlar que haya un registro seleccionado
                if (tbNotas.getSelectedRow() != -1) {
                    //confirmar que el usuario quiere eliminar el registro
                    int opcion = JOptionPane.showConfirmDialog(null, "¿Seguro que desea Eliminar el registro? ", "Confirmación", JOptionPane.YES_NO_OPTION);

                    if (opcion == JOptionPane.YES_OPTION) {

                        int id = (int) tbNotas.getValueAt(tbNotas.getSelectedRow(), 0);
                        //llamda método buscar por ID
                        Nota nota = notaDAO.findById(id);
                        //llamada al método para borrar el registro
                        notaDAO.delete(nota);

                    } else {
                        aux.mostrarMensaje("Registro no eliminado", "Info", "Eliminar registro cancelado");
                    }

                } else {
                    aux.mostrarMensaje("No hay ningún registro seleccionado", "Error", "Error al eliminar");
                }
            } else {
                aux.mostrarMensaje("No hay registros para elimiar", "Error", "Error al eliminar");
            }
        } catch (Exception ex) {
            aux.mostrarMensaje("Error", "Error", "Error al eliminar");
        }

        cargarTabla(notaDAO.findAll());
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed
        cargarTabla(notaDAO.findAll());
    }//GEN-LAST:event_btActualizarActionPerformed

    private void btSobresalientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSobresalientesActionPerformed
        listaBusqueda = notaDAO.findNotasSobresalientes();
        if (listaBusqueda == null || listaBusqueda.isEmpty()) {
            aux.mostrarMensaje("No hay registros de alumnos con un valor de nota sobresaliente", "Error", "Error al editar");
        }
        cargarTabla(listaBusqueda);

    }//GEN-LAST:event_btSobresalientesActionPerformed

    private void btSuspensosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuspensosActionPerformed
        listaBusqueda = notaDAO.findNotasSuspensos();
        if (listaBusqueda == null || listaBusqueda.isEmpty()) {
            aux.mostrarMensaje("NNo hay registros de alumnos con un valor de nota sobresaliente", "Error", "Error al editar");
        }
        cargarTabla(listaBusqueda);
    }//GEN-LAST:event_btSuspensosActionPerformed

    private void btAprobadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAprobadosActionPerformed
        listaBusqueda = notaDAO.findNotasAprobados();
        if (listaBusqueda == null || listaBusqueda.isEmpty()) {
            aux.mostrarMensaje("No hay registros de alumnos con un valor de nota aprobado", "Error", "Error al editar");
        }
        cargarTabla(listaBusqueda);
    }//GEN-LAST:event_btAprobadosActionPerformed

    private void btNotablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNotablesActionPerformed
        listaBusqueda = notaDAO.findNotasNotables();
        if (listaBusqueda == null || listaBusqueda.isEmpty()) {
            aux.mostrarMensaje("No hay registros de alumnos con un valor de nota notable", "Error", "Error al editar");
        }
        cargarTabla(listaBusqueda);
    }//GEN-LAST:event_btNotablesActionPerformed

    private void btPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPdfActionPerformed
        AccionesPDF pdf = new AccionesPDF();
        pdf.crearPlantilla("REGISTROS NOTAS", tbNotas, titulos);
    }//GEN-LAST:event_btPdfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btAprobados;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JButton btNotables;
    private javax.swing.JButton btPdf;
    private javax.swing.JButton btSobresalientes;
    private javax.swing.JButton btSuspensos;
    private javax.swing.JComboBox<String> cmbBuscar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel laTitulo;
    private javax.swing.JPanel pnBotones;
    private javax.swing.JPanel pnBuscar;
    private javax.swing.JScrollPane spTablaNotas;
    private javax.swing.JTable tbNotas;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
String titulos[] = {"ID", "Alumno", "Curso", "Evaluación", "Nota"};

    private void cargarTabla(List<Nota> listaNotas) {
        //definir el modelo de la vista de la Tabla
        DefaultTableModel modeloTabla = new DefaultTableModel() {
            //filas y columnas no editables
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        //establecer nombres en la cabecera de columnas
        modeloTabla.setColumnIdentifiers(titulos);

        //recorrer lista y mostrar los elementos de la tabla
        if (listaNotas != null) {
            for (Nota i : listaNotas) {
                //creamos el array de tipo object porque vamos a guardar diferentes tipos de datos
                Object[] objeto = {i.getId(), i.getAlumno().getNombre() + " " + i.getAlumno().getApellidos(), i.getCurso().getNombre(), i.getEvaluacion(), String.format("%.2f", i.getNota())};

                modeloTabla.addRow(objeto);
            }
        }
        tbNotas.setModel(modeloTabla);
    }

}
