package com.garijotatiana.atomacademy.gui.Pagos;

import com.garijotatiana.atomacademy.Auxiliar;
import com.garijotatiana.atomacademy.DAO.PagoDAO;
import com.garijotatiana.atomacademy.DAO.impl.PagoDAOImplHiber;
import com.garijotatiana.atomacademy.gui.principal.frameAuxiliar;
import com.garijotatiana.atomacademy.model.Pago;
import com.garijotatiana.atomacademy.plantilla.AccionesPDF;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tatiana
 */
public class panelPagos extends javax.swing.JPanel {

    PagoDAO pagoDAO = new PagoDAOImplHiber(Pago.class);
    List<Pago> listaCompleta = pagoDAO.findAll();
    Auxiliar aux = new Auxiliar();

    public panelPagos() {
        initComponents();
        cargarTabla(listaCompleta);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        pnBotones = new javax.swing.JPanel();
        btAdd = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btPdf = new javax.swing.JButton();
        pnBuscar = new javax.swing.JPanel();
        btBuscar = new javax.swing.JButton();
        btLimpiar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        cmbBuscar = new javax.swing.JComboBox<>();
        spTablaPagos = new javax.swing.JScrollPane();
        tbPagos = new javax.swing.JTable();
        laTitulo = new javax.swing.JLabel();
        btActualizar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(870, 620));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(870, 620));

        pnBotones.setOpaque(false);

        btAdd.setBackground(new java.awt.Color(140, 166, 219));
        btAdd.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btAdd.setForeground(new java.awt.Color(255, 255, 255));
        btAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mas.png"))); // NOI18N
        btAdd.setText(" Añadir");
        btAdd.setBorderPainted(false);
        btAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAdd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btEdit.setBackground(new java.awt.Color(140, 166, 219));
        btEdit.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btEdit.setForeground(new java.awt.Color(255, 255, 255));
        btEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lapiz.png"))); // NOI18N
        btEdit.setText(" Editar");
        btEdit.setBorderPainted(false);
        btEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btEdit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        btDelete.setBackground(new java.awt.Color(140, 166, 219));
        btDelete.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btDelete.setForeground(new java.awt.Color(255, 255, 255));
        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/papelera.png"))); // NOI18N
        btDelete.setText(" Eliminar");
        btDelete.setBorderPainted(false);
        btDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDelete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        btPdf.setBackground(new java.awt.Color(140, 166, 219));
        btPdf.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btPdf.setForeground(new java.awt.Color(255, 255, 255));
        btPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pdf.png"))); // NOI18N
        btPdf.setBorderPainted(false);
        btPdf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPdfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnBotonesLayout = new javax.swing.GroupLayout(pnBotones);
        pnBotones.setLayout(pnBotonesLayout);
        pnBotonesLayout.setHorizontalGroup(
            pnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBotonesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btPdf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnBotonesLayout.setVerticalGroup(
            pnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pnBuscar.setOpaque(false);

        btBuscar.setBackground(new java.awt.Color(140, 166, 219));
        btBuscar.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar.png"))); // NOI18N
        btBuscar.setText(" Buscar");
        btBuscar.setBorderPainted(false);
        btBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btBuscar.setMargin(new java.awt.Insets(2, 2, 3, 14));
        btBuscar.setPreferredSize(new java.awt.Dimension(133, 39));
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btLimpiar.setBackground(new java.awt.Color(140, 166, 219));
        btLimpiar.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/borrar.png"))); // NOI18N
        btLimpiar.setText(" Limpiar");
        btLimpiar.setBorderPainted(false);
        btLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLimpiar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btLimpiar.setMargin(new java.awt.Insets(2, 4, 3, 14));
        btLimpiar.setMaximumSize(new java.awt.Dimension(113, 39));
        btLimpiar.setMinimumSize(new java.awt.Dimension(113, 39));
        btLimpiar.setPreferredSize(new java.awt.Dimension(133, 39));
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        cmbBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "FechaPago (Año)", "FechaPago (Completa)", "Periodo", "Alumno", "IDAlumno", "Curso", "Cuota" }));
        cmbBuscar.setBackground(Color.WHITE);
        cmbBuscar.setOpaque(true);

        javax.swing.GroupLayout pnBuscarLayout = new javax.swing.GroupLayout(pnBuscar);
        pnBuscar.setLayout(pnBuscarLayout);
        pnBuscarLayout.setHorizontalGroup(
            pnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbBuscar, 0, 185, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        pnBuscarLayout.setVerticalGroup(
            pnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cmbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPagos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbPagos.setAutoscrolls(false);
        tbPagos.setPreferredSize(new java.awt.Dimension(700, 500));
        tbPagos.setSelectionBackground(new java.awt.Color(140, 166, 219));
        spTablaPagos.setViewportView(tbPagos);

        laTitulo.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        laTitulo.setForeground(new java.awt.Color(79, 79, 255));
        laTitulo.setText("Registros de Pagos");

        btActualizar.setBackground(new java.awt.Color(140, 166, 219));
        btActualizar.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/actualizar.png"))); // NOI18N
        btActualizar.setToolTipText("Actualizar");
        btActualizar.setBorderPainted(false);
        btActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btActualizar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btActualizar.setMargin(new java.awt.Insets(2, 4, 3, 14));
        btActualizar.setMaximumSize(new java.awt.Dimension(113, 39));
        btActualizar.setMinimumSize(new java.awt.Dimension(113, 39));
        btActualizar.setPreferredSize(new java.awt.Dimension(133, 39));
        btActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(spTablaPagos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(laTitulo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(laTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spTablaPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(pnBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    frameAuxiliar pantalla = new frameAuxiliar();
    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        panelNuevoPago panel = new panelNuevoPago();
        JDialog dialogo = new JDialog(pantalla, "Nuevo Registro Pago", true);
        dialogo.setContentPane(panel);
        dialogo.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        dialogo.pack();
        dialogo.setLocationRelativeTo(null);
        dialogo.setVisible(true);

    }//GEN-LAST:event_btAddActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        //controlar que la tabla no esté vacía
        if (tbPagos.getRowCount() > 0) {
            //controlar que haya un registro seleccionado
            if (tbPagos.getSelectedRow() != -1) {
                int id = (int) tbPagos.getValueAt(tbPagos.getSelectedRow(), 0);
                //llamda método buscar por ID
                Pago pago = pagoDAO.findById(id);

                //abrir el panel para editar el registro 
                panelEditarPago panel = new panelEditarPago(pago);

                JDialog dialogo = new JDialog(pantalla, "Editar Registro Pago", true);
                dialogo.setContentPane(panel);
                dialogo.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                dialogo.pack();
                dialogo.setLocationRelativeTo(null);
                dialogo.setVisible(true);

            } else {
                aux.mostrarMensaje("No hay ningún registro seleccionado", "Error", "Error al eliminar");
            }
        } else {
            aux.mostrarMensaje("No hay registros para editar", "Error", "Error al eliminar");
        }

    }//GEN-LAST:event_btEditActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        txtBuscar.setText("");
        cmbBuscar.setSelectedIndex(0);
        cargarTabla(pagoDAO.findAll());
    }//GEN-LAST:event_btLimpiarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        listaCompleta = pagoDAO.findAll();
        List<Pago> listaBusqueda = new ArrayList<>();
        String valorBusqueda = txtBuscar.getText();

        Pattern pattern;
        Matcher matcher;

        try {
            //controlar el el valor de busqueda no esté vacío
            if (!valorBusqueda.isEmpty() && !valorBusqueda.trim().isEmpty()) {
                String propiedad = (String) cmbBuscar.getSelectedItem();

                switch (propiedad) {
                    case "ID":
                        try {
                            int id = Integer.parseInt(valorBusqueda);
                            Pago pago = pagoDAO.findById(id);
                            if (pago != null) {
                                listaBusqueda.add(pago);
                            } else {
                                aux.mostrarMensaje("No encontrado pago con el ID buscado", "Error", "Error al editar");
                            }

                        } catch (NumberFormatException e) {
                            aux.mostrarMensaje("Debe introducir un valor numérico para buscar por ID", "Error", "Error al editar");
                        } catch (Exception e) {
                            aux.mostrarMensaje("Error", "Error", "Error al editar");
                        }

                        break;

                    case "Alumno":
                        listaBusqueda = pagoDAO.findPagosByAlumnoNombreOrApellidos(valorBusqueda);
                        if (listaBusqueda == null) {
                            aux.mostrarMensaje("No encontrado alumo con los datos introducidos", "Error", "Error al editar");
                        }
                        break;

                    case "IDAlumno":
                        listaBusqueda = pagoDAO.findPagosByAlumnoId(valorBusqueda);
                        if (listaBusqueda == null || listaBusqueda.isEmpty()) {
                            aux.mostrarMensaje("No encontrado alumo con el ID introducido", "Error", "Error al editar");
                        }
                        break;

                    case "Curso":
                        listaBusqueda = pagoDAO.findPagosByAlumnoCursoNombre(valorBusqueda);
                        if (listaBusqueda == null || listaBusqueda.isEmpty()) {
                            aux.mostrarMensaje("No encontrado curso con los valores introducidos", "Error", "Error al editar");
                        }
                        break;

                    case "Cuota":
                        try {
                            int cuota = Integer.parseInt(valorBusqueda);
                            for (Pago i : listaCompleta) {
                                if (i.getAlumno().getCuota() == cuota) {
                                    listaBusqueda.add(i);
                                }
                            }

                        } catch (NumberFormatException e) {
                            aux.mostrarMensaje("Debe introducir un valor numérico para buscar por cuota", "Error", "Error al editar");
                        } catch (Exception e) {
                            aux.mostrarMensaje("Error", "Error", "Error al editar");
                        }
                        break;

                    case "Periodo":
                        listaBusqueda = pagoDAO.findLike(propiedad.toLowerCase(), valorBusqueda);
                        if (listaBusqueda == null || listaBusqueda.isEmpty()) {
                            aux.mostrarMensaje("No encontrado registro con los valores introducidos", "Error", "Error al editar");
                        }
                        break;

                    case "FechaPago (Año)":
                        String formatoFechaValido = "^\\d{4}$";
                        pattern = Pattern.compile(formatoFechaValido);
                        matcher = pattern.matcher(valorBusqueda);
                        if (matcher.matches()) {
                            listaBusqueda = pagoDAO.findPagosByFechaAnyo(valorBusqueda);
                            if (listaBusqueda == null || listaBusqueda.isEmpty()) {
                                aux.mostrarMensaje("No encontrado registro fecha de pago con los valores introducidos", "Error", "Error al editar");
                            }
                        } else {
                            aux.mostrarMensaje("El formato del valor a buscar debe coincidir con el año (yyyy)", "Error", "Error al editar");
                        }

                        break;

                    case "FechaPago (Completa)":
                        String formatoFechaComValido = "^[0-9]{4}-[0-9]{2}-[0-9]{2}$";
                        pattern = Pattern.compile(formatoFechaComValido);
                        matcher = pattern.matcher(valorBusqueda);
                        if (matcher.matches()) {
                            LocalDate fecha = LocalDate.parse(valorBusqueda, DateTimeFormatter.ofPattern("yyyy-MM-dd"));
                            listaBusqueda = pagoDAO.findPagosByFechaCompleta(fecha);
                            if (listaBusqueda == null || listaBusqueda.isEmpty()) {
                                aux.mostrarMensaje("No encontrado registro fecha de pago con los valores introducidos", "Error", "Error al editar");
                            }
                        } else {
                            aux.mostrarMensaje("El formato del valor a buscar debe coincidir (yyyy-MM-dd)", "Error", "Error al editar");
                        }

                        break;

                }
                cargarTabla(listaBusqueda);

            } else {
                aux.mostrarMensaje("Debe indicar un criterio de búsqueda", "Error", "Error al editar");
            }

        } catch (Exception e) {

        }

    }//GEN-LAST:event_btBuscarActionPerformed

    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed
        cargarTabla(pagoDAO.findAll());
    }//GEN-LAST:event_btActualizarActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        try {
            //controlar que la tabla no esté vacía
            if (tbPagos.getRowCount() > 0) {
                //controlar que haya un registro seleccionado
                if (tbPagos.getSelectedRow() != -1) {
                    //confirmar que el usuario quiere eliminar el registro
                    int opcion = JOptionPane.showConfirmDialog(null, "¿Seguro que desea Eliminar el registro? ", "Confirmación", JOptionPane.YES_NO_OPTION);

                    if (opcion == JOptionPane.YES_OPTION) {

                        int id = (int) tbPagos.getValueAt(tbPagos.getSelectedRow(), 0);
                        //llamda método buscar por ID
                        Pago pago = pagoDAO.findById(id);
                        //llamada al método para borrar el registro
                        pagoDAO.delete(pago);
                    } else {
                        aux.mostrarMensaje("Registro no eliminado", "Info", "Eliminar registro cancelado");
                    }

                } else {
                    aux.mostrarMensaje("No hay ningún registro seleccionado", "Error", "Error al eliminar");
                }
            } else {
                aux.mostrarMensaje("No hay registros para elimiar", "Error", "Error al eliminar");
            }
        } catch (Exception ex) {
            aux.mostrarMensaje("Error", "Error", "Error al eliminar");
        }

        cargarTabla(pagoDAO.findAll());
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPdfActionPerformed
        AccionesPDF pdf = new AccionesPDF();
        pdf.crearPlantilla("REGISTROS PROFESORES", tbPagos, titulos);
    }//GEN-LAST:event_btPdfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JButton btPdf;
    private javax.swing.JComboBox<String> cmbBuscar;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel laTitulo;
    private javax.swing.JPanel pnBotones;
    private javax.swing.JPanel pnBuscar;
    private javax.swing.JScrollPane spTablaPagos;
    private javax.swing.JTable tbPagos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

    String titulos[] = {"ID", "Periodo", "FechaPago", "ID Alumno", "Alumno", "Cursos", "Cuota"};

    private void cargarTabla(List<Pago> lista) {
        //definir el modelo de la vista de la Tabla
        DefaultTableModel modeloTabla = new DefaultTableModel() {
            //filas y columnas no editables
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        //establecer nombres de columnas
        modeloTabla.setColumnIdentifiers(titulos);

        List<Pago> listaPagos = lista;

        //recorrer lista y mostrar los elementos de la tabla
        if (listaPagos != null) {
            for (Pago i : listaPagos) {
                //creamos el array de tipo object porque vamos a guardar diferentes tipos de datos
                Object[] objeto = {i.getId(), i.getPeriodo(), i.getFecha(), i.getAlumno().getId(), i.getAlumno().getNombre() + " " + i.getAlumno().getApellidos(), i.getAlumno().getNombreCursos(), i.getAlumno().getCuota()};

                modeloTabla.addRow(objeto);
            }
        }
        tbPagos.setModel(modeloTabla);
    }

}
