package com.garijotatiana.atomacademy.gui.Alumno;

import com.garijotatiana.atomacademy.Auxiliar;
import com.garijotatiana.atomacademy.DAO.AlumnoDAO;
import com.garijotatiana.atomacademy.DAO.CursoDAO;
import com.garijotatiana.atomacademy.DAO.impl.AlumnoDAOImplHiber;
import com.garijotatiana.atomacademy.DAO.impl.CursoDAOImplHiber;
import com.garijotatiana.atomacademy.gui.principal.frameAuxiliar;
import com.garijotatiana.atomacademy.model.Alumno;
import com.garijotatiana.atomacademy.model.Curso;
import com.garijotatiana.atomacademy.model.Nota;
import com.garijotatiana.atomacademy.model.Pago;
import com.garijotatiana.atomacademy.plantilla.AccionesPDF;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tatiana
 */
public class panelAlumnos extends javax.swing.JPanel {

    CursoDAO cursoDAO = new CursoDAOImplHiber(Curso.class);
    AlumnoDAO alumnoDAO = new AlumnoDAOImplHiber(Alumno.class);
    Auxiliar aux = new Auxiliar();
    List<Alumno> listaCompleta = alumnoDAO.findAll();

    public panelAlumnos() {
        initComponents();
        cargarTabla(listaCompleta);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgBotonesCrud = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        pnBotones = new javax.swing.JPanel();
        btAdd = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btPdf = new javax.swing.JButton();
        btAddCurso = new javax.swing.JButton();
        pnBuscar = new javax.swing.JPanel();
        btBuscar = new javax.swing.JButton();
        btLimpiar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        cmbBuscar = new javax.swing.JComboBox<>();
        spTablaAlu = new javax.swing.JScrollPane();
        tbAlumnos = new javax.swing.JTable();
        btActualizar = new javax.swing.JButton();
        laTitulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(140, 166, 219));
        setPreferredSize(new java.awt.Dimension(870, 620));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(870, 620));

        pnBotones.setOpaque(false);

        btAdd.setBackground(new java.awt.Color(140, 166, 219));
        btAdd.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btAdd.setForeground(new java.awt.Color(255, 255, 255));
        btAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mas.png"))); // NOI18N
        btAdd.setText(" Añadir");
        btAdd.setBorderPainted(false);
        btAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAdd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btEdit.setBackground(new java.awt.Color(140, 166, 219));
        btEdit.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btEdit.setForeground(new java.awt.Color(255, 255, 255));
        btEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lapiz.png"))); // NOI18N
        btEdit.setText(" Editar");
        btEdit.setBorderPainted(false);
        btEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btEdit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        btDelete.setBackground(new java.awt.Color(140, 166, 219));
        btDelete.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btDelete.setForeground(new java.awt.Color(255, 255, 255));
        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/papelera.png"))); // NOI18N
        btDelete.setText(" Eliminar");
        btDelete.setBorderPainted(false);
        btDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDelete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        btPdf.setBackground(new java.awt.Color(140, 166, 219));
        btPdf.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btPdf.setForeground(new java.awt.Color(255, 255, 255));
        btPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pdf.png"))); // NOI18N
        btPdf.setBorderPainted(false);
        btPdf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPdfActionPerformed(evt);
            }
        });

        btAddCurso.setBackground(new java.awt.Color(140, 166, 219));
        btAddCurso.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btAddCurso.setForeground(new java.awt.Color(255, 255, 255));
        btAddCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eleccion.png"))); // NOI18N
        btAddCurso.setText(" Curso");
        btAddCurso.setBorderPainted(false);
        btAddCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAddCurso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAddCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnBotonesLayout = new javax.swing.GroupLayout(pnBotones);
        pnBotones.setLayout(pnBotonesLayout);
        pnBotonesLayout.setHorizontalGroup(
            pnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBotonesLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(pnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btPdf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAddCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnBotonesLayout.setVerticalGroup(
            pnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAddCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pnBuscar.setOpaque(false);

        btBuscar.setBackground(new java.awt.Color(140, 166, 219));
        btBuscar.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar.png"))); // NOI18N
        btBuscar.setText(" Buscar");
        btBuscar.setBorderPainted(false);
        btBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btBuscar.setMargin(new java.awt.Insets(2, 2, 3, 14));
        btBuscar.setPreferredSize(new java.awt.Dimension(133, 39));
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btLimpiar.setBackground(new java.awt.Color(140, 166, 219));
        btLimpiar.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/borrar.png"))); // NOI18N
        btLimpiar.setText(" Limpiar");
        btLimpiar.setBorderPainted(false);
        btLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLimpiar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btLimpiar.setMargin(new java.awt.Insets(2, 4, 3, 14));
        btLimpiar.setMaximumSize(new java.awt.Dimension(113, 39));
        btLimpiar.setMinimumSize(new java.awt.Dimension(113, 39));
        btLimpiar.setPreferredSize(new java.awt.Dimension(133, 39));
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        cmbBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nombre", "Apellidos", "Documento", "Direccion", "Email", "Teléfono", "Curso", "Cuota" }));
        cmbBuscar.setBackground(Color.WHITE);
        cmbBuscar.setOpaque(true);

        javax.swing.GroupLayout pnBuscarLayout = new javax.swing.GroupLayout(pnBuscar);
        pnBuscar.setLayout(pnBuscarLayout);
        pnBuscarLayout.setHorizontalGroup(
            pnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(cmbBuscar, 0, 191, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        pnBuscarLayout.setVerticalGroup(
            pnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBuscarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbAlumnos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tbAlumnos.setPreferredSize(new java.awt.Dimension(700, 500));
        tbAlumnos.setSelectionBackground(new java.awt.Color(140, 166, 219));
        tbAlumnos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        spTablaAlu.setViewportView(tbAlumnos);

        btActualizar.setBackground(new java.awt.Color(140, 166, 219));
        btActualizar.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/actualizar.png"))); // NOI18N
        btActualizar.setToolTipText("Actualizar");
        btActualizar.setBorderPainted(false);
        btActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btActualizar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btActualizar.setMargin(new java.awt.Insets(2, 4, 3, 14));
        btActualizar.setMaximumSize(new java.awt.Dimension(113, 39));
        btActualizar.setMinimumSize(new java.awt.Dimension(113, 39));
        btActualizar.setPreferredSize(new java.awt.Dimension(133, 39));
        btActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarActionPerformed(evt);
            }
        });

        laTitulo.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        laTitulo.setForeground(new java.awt.Color(79, 79, 255));
        laTitulo.setText("Registros de Alumnos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(spTablaAlu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(laTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(laTitulo)
                    .addComponent(btActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spTablaAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(pnBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    //JFrame auxiliar para cargar el panel según la elección del usuario
    frameAuxiliar pantalla = new frameAuxiliar();
    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        List<Curso> listaCursos = cursoDAO.findAll();
        if (!listaCursos.isEmpty()) {
            panelNuevoAlumno panel = new panelNuevoAlumno();
            JDialog dialogo = new JDialog(pantalla, "Nuevo Registro Alumno", true);
            dialogo.setContentPane(panel);
            dialogo.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            dialogo.pack();
            dialogo.setLocationRelativeTo(null);
            dialogo.setVisible(true);
        } else {
            aux.mostrarMensaje("No hay registros de Cursos", "Info", "Info");
        }

    }//GEN-LAST:event_btAddActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        //controlar que la tabla no esté vacía
        if (tbAlumnos.getRowCount() > 0) {
            //controlar que haya un registro seleccionado
            if (tbAlumnos.getSelectedRow() != -1) {
                //String  id=String.valueOf(tbAlumnos.getValueAt(tbAlumnos.getSelectedRow(),0));
                int id = (int) tbAlumnos.getValueAt(tbAlumnos.getSelectedRow(), 0);
                //llamda método buscar por ID
                Alumno alumno = alumnoDAO.findById(id);
                //abrir interfaz encarcada de editar el registro del empleado
                panelEditarAlumno panel = new panelEditarAlumno(alumno);
                // panelEditarAlumno panel= new panelEditarAlumno(id);
                JDialog dialogo = new JDialog(pantalla, "Editar Registro Alumno", true);
                dialogo.setContentPane(panel);
                dialogo.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                dialogo.pack();
                dialogo.setLocationRelativeTo(null);
                dialogo.setVisible(true);

            } else {
                aux.mostrarMensaje("No hay ningún alumno seleccionado", "Error", "Error al editar");
            }
        } else {
            aux.mostrarMensaje("No hay datos para editar", "Error", "Error al editar");
        }

    }//GEN-LAST:event_btEditActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        List<Alumno> listaBusqueda = new ArrayList<>();
        String valorBusqueda = txtBuscar.getText();

        try {
            //controlar el el valor de busqueda no esté vacío
            if (!valorBusqueda.isEmpty() && !valorBusqueda.trim().isEmpty()) {
                //capo de busqueda
                String propiedad = (String) cmbBuscar.getSelectedItem();

                switch (propiedad) {
                    case "ID":
                        try {
                            int id = Integer.parseInt(valorBusqueda);
                            Alumno alu = alumnoDAO.findById(id);
                            if (alu != null) {
                                listaBusqueda.add(alu);
                            } else {
                                aux.mostrarMensaje("No encontrado alumo con el ID buscado", "Error", "Error al editar");
                            }

                        } catch (NumberFormatException e) {
                            aux.mostrarMensaje("Debe introducir un valor numérico para buscar por ID", "Error", "Error al editar");
                        } catch (Exception e) {
                            aux.mostrarMensaje("Error", "Error", "Error al editar");
                        }

                        break;

                    case "Nombre":
                    case "Email":
                    case "Apellidos":
                    case "Documento":

                        listaBusqueda = alumnoDAO.findLike(propiedad.toLowerCase(), valorBusqueda);
                        if (listaBusqueda == null) {
                            aux.mostrarMensaje("Revise el valor introducido", "Error", "Error al editar");
                        }
                        break;

                    case "Dirección":
                        listaBusqueda = alumnoDAO.findLike("direccion", valorBusqueda);
                        if (listaBusqueda == null) {
                            aux.mostrarMensaje("Revise el valor introducido", "Error", "Error al editar");
                        }
                        break;

                    case "Teléfono":
                        listaBusqueda = alumnoDAO.findLike("telefono", valorBusqueda);
                        if (listaBusqueda == null || listaBusqueda.isEmpty()) {
                            aux.mostrarMensaje("Revise el valor introducido", "Error", "Error al editar");
                        }
                        break;
                    case "Curso":
                        for (Alumno i : alumnoDAO.findAll()) {
                            if (i.getNombreCursos().contains(valorBusqueda)) {
                                listaBusqueda.add(i);
                            }
                        }
                        break;
                    case "Cuota":
                        try {
                            int cuota = Integer.parseInt(valorBusqueda);
                            for (Alumno i : alumnoDAO.findAll()) {
                                if (i.getCuota() == cuota) {
                                    listaBusqueda.add(i);
                                }
                            }

                        } catch (NumberFormatException e) {
                            aux.mostrarMensaje("Debe introducir un valor numérico para buscar por cuota", "Error", "Error al editar");
                        } catch (Exception e) {
                            aux.mostrarMensaje("Error", "Error", "Error al editar");
                        }

                        break;

                }
                cargarTabla(listaBusqueda);

            } else {
                cargarTabla(alumnoDAO.findAll());
                aux.mostrarMensaje("Debe indicar un criterio de búsqueda", "Error", "Error al editar");
            }

        } catch (Exception e) {
            aux.mostrarMensaje("Revise la conexión", "Error", "Error");
        }


    }//GEN-LAST:event_btBuscarActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        txtBuscar.setText("");
        cmbBuscar.setSelectedIndex(0);

        cargarTabla(alumnoDAO.findAll());
    }//GEN-LAST:event_btLimpiarActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        try {
            //controlar que la tabla no esté vacía
            if (tbAlumnos.getRowCount() > 0) {
                //controlar que haya un registro seleccionado
                if (tbAlumnos.getSelectedRow() != -1) {

                    int opcion = JOptionPane.showConfirmDialog(null, "¿Seguro que desea Eliminar el registro? ", "Confirmación", JOptionPane.YES_NO_OPTION);

                    if (opcion == JOptionPane.YES_OPTION) {

                        int id = (int) tbAlumnos.getValueAt(tbAlumnos.getSelectedRow(), 0);
                        //llamda método buscar por ID
                        Alumno alumno = alumnoDAO.findById(id);
                        //comprobar si tiene pagos o notas asociadas
                        List<Pago> listaPagos = alumno.getPagos();
                        List<Nota> listaNotas = alumno.getNotas();

                        if (!listaPagos.isEmpty() && listaPagos != null) {
                            aux.mostrarMensaje("Este Alumno no se puede eliminar, tiene registros de pagos ", "Error", "Error al eliminar");
                        } else if (!listaNotas.isEmpty() && listaNotas != null) {
                            aux.mostrarMensaje("Este Alumno no se puede eliminar, tiene registros de notas ", "Error", "Error al eliminar");
                        } else {
                            //llamada al método para borrar el registro
                            alumnoDAO.delete(alumno);
                        }

                    } else {
                        aux.mostrarMensaje("Registro no eliminado", "Info", "Eliminar registro cancelado");
                    }

                } else {
                    aux.mostrarMensaje("No hay ningún registro seleccionado", "Error", "Error al eliminar");
                }
            } else {
                aux.mostrarMensaje("No hay registros para elimiar", "Error", "Error al eliminar");
            }
        } catch (Exception ex) {
            aux.mostrarMensaje("Error", "Error", "Error al eliminar");
        }

        cargarTabla(alumnoDAO.findAll());
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btAddCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddCursoActionPerformed
        //controlar que la tabla no esté vacía
        if (tbAlumnos.getRowCount() > 0) {
            //controlar que haya un registro seleccionado
            if (tbAlumnos.getSelectedRow() != -1) {

                int id = (int) tbAlumnos.getValueAt(tbAlumnos.getSelectedRow(), 0);
                //Comprobar si hay cursos registrados
                List<Curso> listaCursos = cursoDAO.findAll();
                if (!listaCursos.isEmpty()) {

                    //llamda método buscar por ID
                    Alumno alumno = alumnoDAO.findById(id);
                    //abrir interfaz encarcada de editar el registro del empleado
                    panelAlumnoAnyadirCurso panel = new panelAlumnoAnyadirCurso(alumno);
                    // panelEditarAlumno panel= new panelEditarAlumno(id);
                    JDialog dialogo = new JDialog(pantalla, "Añadir Curso a Alumno", true);
                    dialogo.setContentPane(panel);
                    dialogo.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                    dialogo.pack();
                    dialogo.setLocationRelativeTo(null);
                    dialogo.setVisible(true);
                    
                } else {
                    aux.mostrarMensaje("No hay registros de Cursos", "Info", "Info");
                }

            } else {
                aux.mostrarMensaje("No hay ningún alumno seleccionado", "Error", "Error al editar");
            }
        } else {
            aux.mostrarMensaje("No hay datos para editar", "Error", "Error al editar");
        }
    }//GEN-LAST:event_btAddCursoActionPerformed

    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed

        try {
            cargarTabla(alumnoDAO.findAll());
        } catch (Exception ex) {
            aux.mostrarMensaje("Revise la conexión", "Error", "Error");
        }
    }//GEN-LAST:event_btActualizarActionPerformed

    private void btPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPdfActionPerformed
        AccionesPDF pdf = new AccionesPDF();
        pdf.crearPlantilla("REGISTROS ALUMNOS", tbAlumnos, titulos);

    }//GEN-LAST:event_btPdfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgBotonesCrud;
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btAddCurso;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JButton btPdf;
    private javax.swing.JComboBox<String> cmbBuscar;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel laTitulo;
    public javax.swing.JPanel pnBotones;
    private javax.swing.JPanel pnBuscar;
    private javax.swing.JScrollPane spTablaAlu;
    private javax.swing.JTable tbAlumnos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

    String titulos[] = {"ID", "Nombre", "Documento", "Teléfono", "Dirección", "Email", "Cursos", "Cuota"};

    private void cargarTabla(List<Alumno> lista) {
        //definir el modelo de la vista de la Tabla
        DefaultTableModel modeloTabla = new DefaultTableModel() {
            //filas y columnas no editables
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        //establecer nombres de columnas
        modeloTabla.setColumnIdentifiers(titulos);

        List<Alumno> listaAlumnos = lista;

        //recorrer lista y mostrar los elementos de la tabla
        if (listaAlumnos != null) {
            for (Alumno i : listaAlumnos) {
                //creamos el array de tipo object porque vamos a guardar diferentes tipos de datos
                Object[] objeto = {i.getId(), i.getNombre() + " " + i.getApellidos(), i.getDocumento(), i.getTelefono(), i.getDireccion(), i.getEmail(), i.getNombreCursos(), i.getCuota()};

                modeloTabla.addRow(objeto);
            }
        }
        tbAlumnos.setModel(modeloTabla);
    }

}
