package com.garijotatiana.atomacademy.gui.Alumno;

import com.garijotatiana.atomacademy.Auxiliar;
import com.garijotatiana.atomacademy.DAO.AlumnoDAO;
import com.garijotatiana.atomacademy.DAO.CursoDAO;
import com.garijotatiana.atomacademy.DAO.impl.AlumnoDAOImplHiber;
import com.garijotatiana.atomacademy.DAO.impl.CursoDAOImplHiber;
import com.garijotatiana.atomacademy.model.Alumno;
import com.garijotatiana.atomacademy.model.Curso;
import java.awt.Color;
import java.awt.Window;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.SwingUtilities;
/**
 *
 * @author Tatiana
 */
public class panelAlumnoAnyadirCurso extends javax.swing.JPanel {

    Alumno alumno;
    CursoDAO cursoDAO = new CursoDAOImplHiber(Curso.class);
    AlumnoDAO alumnoDAO = new AlumnoDAOImplHiber(Alumno.class);
    Auxiliar aux = new Auxiliar();

    public panelAlumnoAnyadirCurso(Alumno alumno) {
        this.alumno = alumno;
        initComponents();
        cargarComboCursos();
        cargarDatos(alumno);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pDatosAlu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btQuitar = new javax.swing.JButton();
        btAdd = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtDoc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbCurso = new javax.swing.JComboBox<>();
        txtTelefono = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtIDAlumno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ftxtFechaNac = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(670, 550));

        pDatosAlu.setBackground(new java.awt.Color(255, 255, 255));
        pDatosAlu.setPreferredSize(new java.awt.Dimension(670, 550));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(79, 79, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nombre: ");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(79, 79, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Apellidos:");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(79, 79, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Dirección:");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(79, 79, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Documento:");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(79, 79, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Teléfono:");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(79, 79, 255));
        jLabel6.setText("Fecha nac.:");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fecha.png"))); // NOI18N

        btQuitar.setBackground(new java.awt.Color(140, 166, 219));
        btQuitar.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        btQuitar.setForeground(new java.awt.Color(255, 255, 255));
        btQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resta.png"))); // NOI18N
        btQuitar.setText(" Quitar");
        btQuitar.setBorderPainted(false);
        btQuitar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btQuitar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btQuitar.setPreferredSize(new java.awt.Dimension(149, 39));
        btQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuitarActionPerformed(evt);
            }
        });

        btAdd.setBackground(new java.awt.Color(140, 166, 219));
        btAdd.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        btAdd.setForeground(new java.awt.Color(255, 255, 255));
        btAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mas.png"))); // NOI18N
        btAdd.setText(" Añadir");
        btAdd.setBorderPainted(false);
        btAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAdd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAdd.setPreferredSize(new java.awt.Dimension(149, 39));
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(223, 223, 249));
        txtNombre.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(102, 102, 102));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombre.setActionCommand("<Not Set>");
        txtNombre.setBorder(null);
        txtNombre.setOpaque(true);

        txtDireccion.setEditable(false);
        txtDireccion.setBackground(new java.awt.Color(223, 223, 249));
        txtDireccion.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(102, 102, 102));
        txtDireccion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDireccion.setActionCommand("<Not Set>");
        txtDireccion.setBorder(null);
        txtDireccion.setOpaque(true);

        txtApellidos.setEditable(false);
        txtApellidos.setBackground(new java.awt.Color(223, 223, 249));
        txtApellidos.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtApellidos.setForeground(new java.awt.Color(102, 102, 102));
        txtApellidos.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtApellidos.setActionCommand("<Not Set>");
        txtApellidos.setBorder(null);
        txtApellidos.setOpaque(true);

        txtDoc.setEditable(false);
        txtDoc.setBackground(new java.awt.Color(223, 223, 249));
        txtDoc.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtDoc.setForeground(new java.awt.Color(102, 102, 102));
        txtDoc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDoc.setToolTipText("");
        txtDoc.setActionCommand("<Not Set>");
        txtDoc.setBorder(null);
        txtDoc.setOpaque(true);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(79, 79, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Curso:");

        cmbCurso.setBackground(Color.WHITE);
        cmbCurso.setOpaque(true);

        txtTelefono.setEditable(false);
        txtTelefono.setBackground(new java.awt.Color(223, 223, 249));
        txtTelefono.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(102, 102, 102));
        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTelefono.setActionCommand("<Not Set>");
        txtTelefono.setBorder(null);
        txtTelefono.setOpaque(true);

        txtEmail.setEditable(false);
        txtEmail.setBackground(new java.awt.Color(223, 223, 249));
        txtEmail.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(102, 102, 102));
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEmail.setActionCommand("<Not Set>");
        txtEmail.setBorder(null);
        txtEmail.setOpaque(true);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(79, 79, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Email:");

        txtIDAlumno.setEditable(false);
        txtIDAlumno.setBackground(new java.awt.Color(223, 223, 249));
        txtIDAlumno.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtIDAlumno.setForeground(new java.awt.Color(102, 102, 102));
        txtIDAlumno.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIDAlumno.setActionCommand("<Not Set>");
        txtIDAlumno.setBorder(null);
        txtIDAlumno.setOpaque(true);

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(79, 79, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("ID: ");

        ftxtFechaNac.setEditable(false);
        ftxtFechaNac.setBackground(new java.awt.Color(223, 223, 249));
        try {
            ftxtFechaNac.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtFechaNac.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout pDatosAluLayout = new javax.swing.GroupLayout(pDatosAlu);
        pDatosAlu.setLayout(pDatosAluLayout);
        pDatosAluLayout.setHorizontalGroup(
            pDatosAluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDatosAluLayout.createSequentialGroup()
                .addGroup(pDatosAluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDatosAluLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(pDatosAluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDatosAluLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pDatosAluLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pDatosAluLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pDatosAluLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pDatosAluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pDatosAluLayout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtIDAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pDatosAluLayout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pDatosAluLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(pDatosAluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDatosAluLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ftxtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9))
                            .addGroup(pDatosAluLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(pDatosAluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pDatosAluLayout.createSequentialGroup()
                                        .addComponent(btQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(66, 66, 66)
                                        .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cmbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pDatosAluLayout.setVerticalGroup(
            pDatosAluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDatosAluLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pDatosAluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtIDAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pDatosAluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pDatosAluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pDatosAluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pDatosAluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pDatosAluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDatosAluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pDatosAluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pDatosAluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(ftxtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(pDatosAluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pDatosAluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("121");
        jLabel2.getAccessibleContext().setAccessibleName("121");
        jLabel3.getAccessibleContext().setAccessibleName("121");
        jLabel4.getAccessibleContext().setAccessibleName("121");
        jLabel5.getAccessibleContext().setAccessibleName("121");
        jLabel7.getAccessibleContext().setAccessibleName("121");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pDatosAlu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pDatosAlu, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuitarActionPerformed
        try {
            String nombreCurso = (String) cmbCurso.getSelectedItem();
            Curso curso = cursoDAO.findByName(nombreCurso);
            
            //comprobar si el alumno pertenece al curos
            boolean tieneCurso = alumno.getCursos().stream().anyMatch(c -> c.getNombre().equals(nombreCurso));
            
            if (tieneCurso) {//si pertenece se elimina de su lista y se actualiza el registro

                //recorrer la lista y eliminar el curso que que coincida con la id
                alumno.getCursos().removeIf(c -> c.getNombre().equals(nombreCurso));
                
                curso.getAlumnos().remove(alumno);

                cursoDAO.update(curso);
                alumnoDAO.update(alumno);

                aux.mostrarMensaje("El Alumno ya no pertenece al curso " + " " + curso.getNombre(), "Info", "Info");
                
                Window parent = SwingUtilities.getWindowAncestor(this);
                parent.dispose();

            } else {
                aux.mostrarMensaje("El Alumno no pertenece al curso " + " " + curso.getNombre(), "Error", "Error");
            }

        } catch (Exception ex) {
            aux.mostrarMensaje("Error al Quitar el Curso ", "Error", "Error");
        }
    }//GEN-LAST:event_btQuitarActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        try {
            String nombreCurso = (String) cmbCurso.getSelectedItem();
            Curso curso = cursoDAO.findByName(nombreCurso);
            
            //comprobar si el alumno pertenece al curos
            boolean tieneCurso = alumno.getCursos().stream().anyMatch(c -> c.getNombre().equals(nombreCurso));
            
            if (!tieneCurso) {//si no pertenece al curso
                //si el curso no está completo se añade el registro
                if (!curso.isCompleto()) {
                    alumno.getCursos().add(curso);
                    curso.getAlumnos().add(alumno);
                    
                    
                    alumnoDAO.update(alumno);

                    cursoDAO.update(curso);

                    aux.mostrarMensaje("Alumno inscrito al curso " + " " + curso.getNombre(), "Info", "Info");

                    Window parent = SwingUtilities.getWindowAncestor(this);
                    parent.dispose();
                } else {
                    aux.mostrarMensaje("El curso está completo ", "Error", "Error");
                }
            } else {
                aux.mostrarMensaje("El Alumno ya pertenece a ese curso ", "Error", "Error");
            }
        } catch (Exception ex) {
            aux.mostrarMensaje("Error al Añadir el Curso ", "Error", "Error");
        }
    }//GEN-LAST:event_btAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btQuitar;
    private javax.swing.JComboBox<String> cmbCurso;
    private javax.swing.JFormattedTextField ftxtFechaNac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pDatosAlu;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDoc;
    private javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtIDAlumno;
    public javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    //cargar al formulario los datos del alumno seleccionado
    private void cargarDatos(Alumno alu) {
        try {
            txtIDAlumno.setText(Integer.toString(alu.getId()));
            txtDoc.setText(alu.getDocumento());
            txtNombre.setText(alu.getNombre());
            txtApellidos.setText(alu.getApellidos());
            txtDireccion.setText(alu.getDireccion());
            txtEmail.setText(alu.getEmail());
            txtTelefono.setText(alu.getTelefono());
            ftxtFechaNac.setText(alumno.getFechaNac().format(DateTimeFormatter.ofPattern("yyyy-MM-dd")));

            txtNombre.requestFocus();
        } catch (Exception e) {
            aux.mostrarMensaje("ERROR ", "Error", "Error");
        }
    }

    //cargar al combobox los nombres de los cursos desde la BD
    private void cargarComboCursos() {
        List<Curso> listaCursos = cursoDAO.findAll();

        try {

            if (listaCursos != null) {
                for (Curso resultado : listaCursos) {
                    cmbCurso.addItem(resultado.getNombre());
                }
            }
        } catch (Exception ex) {
            aux.mostrarMensaje("Error al cargar los datos, Actualice los Cursos", "Error", "Error");
        }
    }

}
